### ISSUE TITLE
mfa_token login issues

### ISSUE THREAD

**Issue by chinmayjade** [jaron-l/mintapi#1]
Hi, I followed your recommendation on issue #258 to create a 2FA authenticator key and I am passing the mfa_token which is the manual_key.
However, it seems like mintapi is still landing on a login screen where an MFA code is sent to email and I get the following errors:

`Traceback (most recent call last):
  File "/Users/cjade/Documents/GitHub/Mint_Sheets_Budgets/logic.py", line 9, in <module>
    mint = mintapi.Mint(
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/mintapi/api.py", line 515, in __init__
    self.login_and_get_token(email, password,
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/mintapi/api.py", line 603, in login_and_get_token
    self.driver, self.status_message = get_web_driver(
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/mintapi/api.py", line 434, in get_web_driver
    _sign_in(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, imap_account,
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/mintapi/api.py", line 364, in _sign_in
    mfa_token_input.send_keys(mfa_code)
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/cjade/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=92.0.4515.159)`

I have correctly set `mfa_method='soft-token'` and `mfa_token=manual_key`
`manual_key` is a var which stores the manual key from intuit.

Can you please help in checking what is going on and how to resole this?

**Comment by chinmayjade** [comment]
I opened this issue on the this branch by mistake. Should I close and open on the master?
